// Generated by gencpp from file mtt/TargetListPC.msg
// DO NOT EDIT!


#ifndef MTT_MESSAGE_TARGETLISTPC_H
#define MTT_MESSAGE_TARGETLISTPC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>

namespace mtt
{
template <class ContainerAllocator>
struct TargetListPC_
{
  typedef TargetListPC_<ContainerAllocator> Type;

  TargetListPC_()
    : header()
    , id()
    , position()
    , velocity()
    , obstacle_lines()  {
    }
  TargetListPC_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , obstacle_lines(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _id_type;
  _id_type id;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::other >  _obstacle_lines_type;
  _obstacle_lines_type obstacle_lines;





  typedef boost::shared_ptr< ::mtt::TargetListPC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mtt::TargetListPC_<ContainerAllocator> const> ConstPtr;

}; // struct TargetListPC_

typedef ::mtt::TargetListPC_<std::allocator<void> > TargetListPC;

typedef boost::shared_ptr< ::mtt::TargetListPC > TargetListPCPtr;
typedef boost::shared_ptr< ::mtt::TargetListPC const> TargetListPCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mtt::TargetListPC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mtt::TargetListPC_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mtt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'mtt': ['/home/ruic7/MTT/src/mtt/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mtt::TargetListPC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mtt::TargetListPC_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mtt::TargetListPC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mtt::TargetListPC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mtt::TargetListPC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mtt::TargetListPC_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mtt::TargetListPC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc4e1ab399de53d9a4d2b0838677506f";
  }

  static const char* value(const ::mtt::TargetListPC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc4e1ab399de53d9ULL;
  static const uint64_t static_value2 = 0xa4d2b0838677506fULL;
};

template<class ContainerAllocator>
struct DataType< ::mtt::TargetListPC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mtt/TargetListPC";
  }

  static const char* value(const ::mtt::TargetListPC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mtt::TargetListPC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#the header of the message\n"
"Header header\n"
"uint32[] id\n"
"sensor_msgs/PointCloud2 position\n"
"sensor_msgs/PointCloud2 velocity\n"
"sensor_msgs/PointCloud2[] obstacle_lines\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::mtt::TargetListPC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mtt::TargetListPC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.obstacle_lines);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TargetListPC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mtt::TargetListPC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mtt::TargetListPC_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "position: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "obstacle_lines[]" << std::endl;
    for (size_t i = 0; i < v.obstacle_lines.size(); ++i)
    {
      s << indent << "  obstacle_lines[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacle_lines[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MTT_MESSAGE_TARGETLISTPC_H
