// Generated by gencpp from file odometer/OdometerStatus.msg
// DO NOT EDIT!


#ifndef ODOMETER_MESSAGE_ODOMETERSTATUS_H
#define ODOMETER_MESSAGE_ODOMETERSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace odometer
{
template <class ContainerAllocator>
struct OdometerStatus_
{
  typedef OdometerStatus_<ContainerAllocator> Type;

  OdometerStatus_()
    : header()
    , count(0.0)
    , pulses_sec(0.0)
    , revolutions_sec(0.0)
    , velocity(0.0)  {
    }
  OdometerStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , count(0.0)
    , pulses_sec(0.0)
    , revolutions_sec(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _count_type;
  _count_type count;

   typedef double _pulses_sec_type;
  _pulses_sec_type pulses_sec;

   typedef double _revolutions_sec_type;
  _revolutions_sec_type revolutions_sec;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::odometer::OdometerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odometer::OdometerStatus_<ContainerAllocator> const> ConstPtr;

}; // struct OdometerStatus_

typedef ::odometer::OdometerStatus_<std::allocator<void> > OdometerStatus;

typedef boost::shared_ptr< ::odometer::OdometerStatus > OdometerStatusPtr;
typedef boost::shared_ptr< ::odometer::OdometerStatus const> OdometerStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odometer::OdometerStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odometer::OdometerStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace odometer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'odometer': ['/home/ruic7/mymtt/src/sensors/odometer/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::odometer::OdometerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odometer::OdometerStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometer::OdometerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometer::OdometerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometer::OdometerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometer::OdometerStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odometer::OdometerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4addd405435fa107b3c310744e623fd6";
  }

  static const char* value(const ::odometer::OdometerStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4addd405435fa107ULL;
  static const uint64_t static_value2 = 0xb3c310744e623fd6ULL;
};

template<class ContainerAllocator>
struct DataType< ::odometer::OdometerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odometer/OdometerStatus";
  }

  static const char* value(const ::odometer::OdometerStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odometer::OdometerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 count\n"
"float64 pulses_sec\n"
"float64 revolutions_sec\n"
"float64 velocity\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::odometer::OdometerStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odometer::OdometerStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.count);
      stream.next(m.pulses_sec);
      stream.next(m.revolutions_sec);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdometerStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odometer::OdometerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odometer::OdometerStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "count: ";
    Printer<double>::stream(s, indent + "  ", v.count);
    s << indent << "pulses_sec: ";
    Printer<double>::stream(s, indent + "  ", v.pulses_sec);
    s << indent << "revolutions_sec: ";
    Printer<double>::stream(s, indent + "  ", v.revolutions_sec);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODOMETER_MESSAGE_ODOMETERSTATUS_H
