(cl:in-package atlascar_base-msg)
(cl:export '(HEADER-VAL
          HEADER
          CLUTCH-VAL
          CLUTCH
          BRAKE-VAL
          BRAKE
          STEERING_WHEEL-VAL
          STEERING_WHEEL
          RPM-VAL
          RPM
          LIGHTS_HIGH-VAL
          LIGHTS_HIGH
          LIGHTS_MEDIUM-VAL
          LIGHTS_MEDIUM
          LIGHTS_MINIMUM-VAL
          LIGHTS_MINIMUM
          LIGHTS_LEFT-VAL
          LIGHTS_LEFT
          LIGHTS_RIGHT-VAL
          LIGHTS_RIGHT
          LIGHTS_BRAKE-VAL
          LIGHTS_BRAKE
          LIGHTS_REVERSE-VAL
          LIGHTS_REVERSE
          LIGHTS_WARNING-VAL
          LIGHTS_WARNING
          IGNITION-VAL
          IGNITION
          EMERGENCY-VAL
          EMERGENCY
          AUTO_IGNITION-VAL
          AUTO_IGNITION
          AUTO_BRAKE-VAL
          AUTO_BRAKE
          AUTO_DIRECTION-VAL
          AUTO_DIRECTION
          AUTO_CLUTCH-VAL
          AUTO_CLUTCH
          PRIORITY-VAL
          PRIORITY
          LIFETIME-VAL
          LIFETIME
))