(cl:in-package atlascar_base-msg)
(cl:export '(HEADER-VAL
          HEADER
          GEAR-VAL
          GEAR
          GEARBOX_STATUS-VAL
          GEARBOX_STATUS
          CLUTCH-VAL
          CLUTCH
          BRAKE-VAL
          BRAKE
          STEERING_WHEEL-VAL
          STEERING_WHEEL
          RPM-VAL
          RPM
          LIGHTS_BRAKE-VAL
          LIGHTS_BRAKE
          LIGHTS_REVERSE-VAL
          LIGHTS_REVERSE
          LIGHTS_WARNING-VAL
          LIGHTS_WARNING
          EMERGENCY-VAL
          EMERGENCY
          AUTO_IGNITION-VAL
          AUTO_IGNITION
          AUTO_BRAKE-VAL
          AUTO_BRAKE
          AUTO_DIRECTION-VAL
          AUTO_DIRECTION
          AUTO_CLUTCH-VAL
          AUTO_CLUTCH
          THROTTLE-VAL
          THROTTLE
          THROTTLE_PEDAL-VAL
          THROTTLE_PEDAL
          AUTO_THROTTLE-VAL
          AUTO_THROTTLE
          VELOCITY-VAL
          VELOCITY
          COUNT-VAL
          COUNT
          PULSES_SEC-VAL
          PULSES_SEC
          REVOLUTIONS_SEC-VAL
          REVOLUTIONS_SEC
          LIGHTS_HIGH-VAL
          LIGHTS_HIGH
          LIGHTS_MEDIUM-VAL
          LIGHTS_MEDIUM
          LIGHTS_LEFT-VAL
          LIGHTS_LEFT
          LIGHTS_RIGHT-VAL
          LIGHTS_RIGHT
          LIGHTS_DANGER-VAL
          LIGHTS_DANGER
          IGNITION-VAL
          IGNITION
          HORN-VAL
          HORN
          THROTTLE_PRESSURE-VAL
          THROTTLE_PRESSURE
          BRAKE_PRESSURE-VAL
          BRAKE_PRESSURE
          CLUTCH_PRESSURE-VAL
          CLUTCH_PRESSURE
))