(cl:defpackage atlascar_base-msg
  (:use )
  (:export
   "<GEARBOXCOMMAND>"
   "GEARBOXCOMMAND"
   "<GEARBOXSTATUS>"
   "GEARBOXSTATUS"
   "<MANAGERCOMMAND>"
   "MANAGERCOMMAND"
   "<MANAGERSTATUS>"
   "MANAGERSTATUS"
   "<PLCCOMMAND>"
   "PLCCOMMAND"
   "<PLCSTATUS>"
   "PLCSTATUS"
   "<THROTTLECOMMAND>"
   "THROTTLECOMMAND"
   "<THROTTLESTATUS>"
   "THROTTLESTATUS"
  ))

