(cl:in-package atlascar_base-msg)
(cl:export '(HEADER-VAL
          HEADER
          PRIORITY-VAL
          PRIORITY
          LIFETIME-VAL
          LIFETIME
          GEAR-VAL
          GEAR
          CLUTCH-VAL
          CLUTCH
          BRAKE-VAL
          BRAKE
          STEERING_WHEEL-VAL
          STEERING_WHEEL
          THROTTLE-VAL
          THROTTLE
          VELOCITY-VAL
          VELOCITY
          LIGHTS_BRAKE-VAL
          LIGHTS_BRAKE
          LIGHTS_REVERSE-VAL
          LIGHTS_REVERSE
          LIGHTS_WARNING-VAL
          LIGHTS_WARNING
          LIGHTS_HIGH-VAL
          LIGHTS_HIGH
          LIGHTS_MEDIUM-VAL
          LIGHTS_MEDIUM
          LIGHTS_LEFT-VAL
          LIGHTS_LEFT
          LIGHTS_RIGHT-VAL
          LIGHTS_RIGHT
          LIGHTS_DANGER-VAL
          LIGHTS_DANGER
          EMERGENCY-VAL
          EMERGENCY
          AUTO_IGNITION-VAL
          AUTO_IGNITION
          AUTO_BRAKE-VAL
          AUTO_BRAKE
          AUTO_DIRECTION-VAL
          AUTO_DIRECTION
          AUTO_CLUTCH-VAL
          AUTO_CLUTCH
          AUTO_THROTTLE-VAL
          AUTO_THROTTLE
          PARKING-VAL
          PARKING
          IGNITION-VAL
          IGNITION
          HORN-VAL
          HORN
          DIRECT_CONTROL-VAL
          DIRECT_CONTROL
))