// Generated by gencpp from file atlascar_base/ThrottleStatus.msg
// DO NOT EDIT!


#ifndef ATLASCAR_BASE_MESSAGE_THROTTLESTATUS_H
#define ATLASCAR_BASE_MESSAGE_THROTTLESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace atlascar_base
{
template <class ContainerAllocator>
struct ThrottleStatus_
{
  typedef ThrottleStatus_<ContainerAllocator> Type;

  ThrottleStatus_()
    : header()
    , throttle(0.0)
    , footPedal(0.0)
    , mode(0)  {
    }
  ThrottleStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , throttle(0.0)
    , footPedal(0.0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _throttle_type;
  _throttle_type throttle;

   typedef double _footPedal_type;
  _footPedal_type footPedal;

   typedef uint32_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::atlascar_base::ThrottleStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::atlascar_base::ThrottleStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ThrottleStatus_

typedef ::atlascar_base::ThrottleStatus_<std::allocator<void> > ThrottleStatus;

typedef boost::shared_ptr< ::atlascar_base::ThrottleStatus > ThrottleStatusPtr;
typedef boost::shared_ptr< ::atlascar_base::ThrottleStatus const> ThrottleStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::atlascar_base::ThrottleStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::atlascar_base::ThrottleStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace atlascar_base

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'atlascar_base': ['/home/ruic7/mymtt/src/atlascar_base/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::atlascar_base::ThrottleStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::atlascar_base::ThrottleStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atlascar_base::ThrottleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::atlascar_base::ThrottleStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atlascar_base::ThrottleStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::atlascar_base::ThrottleStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::atlascar_base::ThrottleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f0f061e0791f9ddcde2a12e67cbfa4d";
  }

  static const char* value(const ::atlascar_base::ThrottleStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f0f061e0791f9ddULL;
  static const uint64_t static_value2 = 0xcde2a12e67cbfa4dULL;
};

template<class ContainerAllocator>
struct DataType< ::atlascar_base::ThrottleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "atlascar_base/ThrottleStatus";
  }

  static const char* value(const ::atlascar_base::ThrottleStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::atlascar_base::ThrottleStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float64 throttle\n"
"float64 footPedal\n"
"uint32 mode\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::atlascar_base::ThrottleStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::atlascar_base::ThrottleStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.throttle);
      stream.next(m.footPedal);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrottleStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::atlascar_base::ThrottleStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::atlascar_base::ThrottleStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "footPedal: ";
    Printer<double>::stream(s, indent + "  ", v.footPedal);
    s << indent << "mode: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ATLASCAR_BASE_MESSAGE_THROTTLESTATUS_H
