# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from human_driver_monitor/HumanDriverMonitorStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class HumanDriverMonitorStatus(genpy.Message):
  _md5sum = "e0f0d2c30fd975b578f76d6ff646b0d4"
  _type = "human_driver_monitor/HumanDriverMonitorStatus"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

uint32 lights_high
uint32 lights_medium
uint32 lights_left
uint32 lights_right
uint32 lights_danger

uint32 ignition

uint32 horn

uint32 throttle_pressure
uint32 brake_pressure
uint32 clutch_pressure

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','lights_high','lights_medium','lights_left','lights_right','lights_danger','ignition','horn','throttle_pressure','brake_pressure','clutch_pressure']
  _slot_types = ['std_msgs/Header','uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,lights_high,lights_medium,lights_left,lights_right,lights_danger,ignition,horn,throttle_pressure,brake_pressure,clutch_pressure

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HumanDriverMonitorStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.lights_high is None:
        self.lights_high = 0
      if self.lights_medium is None:
        self.lights_medium = 0
      if self.lights_left is None:
        self.lights_left = 0
      if self.lights_right is None:
        self.lights_right = 0
      if self.lights_danger is None:
        self.lights_danger = 0
      if self.ignition is None:
        self.ignition = 0
      if self.horn is None:
        self.horn = 0
      if self.throttle_pressure is None:
        self.throttle_pressure = 0
      if self.brake_pressure is None:
        self.brake_pressure = 0
      if self.clutch_pressure is None:
        self.clutch_pressure = 0
    else:
      self.header = std_msgs.msg.Header()
      self.lights_high = 0
      self.lights_medium = 0
      self.lights_left = 0
      self.lights_right = 0
      self.lights_danger = 0
      self.ignition = 0
      self.horn = 0
      self.throttle_pressure = 0
      self.brake_pressure = 0
      self.clutch_pressure = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_10I().pack(_x.lights_high, _x.lights_medium, _x.lights_left, _x.lights_right, _x.lights_danger, _x.ignition, _x.horn, _x.throttle_pressure, _x.brake_pressure, _x.clutch_pressure))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.lights_high, _x.lights_medium, _x.lights_left, _x.lights_right, _x.lights_danger, _x.ignition, _x.horn, _x.throttle_pressure, _x.brake_pressure, _x.clutch_pressure,) = _get_struct_10I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_10I().pack(_x.lights_high, _x.lights_medium, _x.lights_left, _x.lights_right, _x.lights_danger, _x.ignition, _x.horn, _x.throttle_pressure, _x.brake_pressure, _x.clutch_pressure))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.lights_high, _x.lights_medium, _x.lights_left, _x.lights_right, _x.lights_danger, _x.ignition, _x.horn, _x.throttle_pressure, _x.brake_pressure, _x.clutch_pressure,) = _get_struct_10I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_10I = None
def _get_struct_10I():
    global _struct_10I
    if _struct_10I is None:
        _struct_10I = struct.Struct("<10I")
    return _struct_10I
