# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from atlascar_base/PlcCommand.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class PlcCommand(genpy.Message):
  _md5sum = "efb734467385cefb807dd165a73e2077"
  _type = "atlascar_base/PlcCommand"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

float64 clutch
float64 brake
float64 steering_wheel
float64 rpm

uint32 lights_high
uint32 lights_medium
uint32 lights_minimum
uint32 lights_left
uint32 lights_right
uint32 lights_brake
uint32 lights_reverse
uint32 lights_warning

uint32 ignition
uint32 emergency

uint32 auto_ignition
uint32 auto_brake
uint32 auto_direction
uint32 auto_clutch

float64 priority
float64 lifetime
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','clutch','brake','steering_wheel','rpm','lights_high','lights_medium','lights_minimum','lights_left','lights_right','lights_brake','lights_reverse','lights_warning','ignition','emergency','auto_ignition','auto_brake','auto_direction','auto_clutch','priority','lifetime']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32','uint32','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,clutch,brake,steering_wheel,rpm,lights_high,lights_medium,lights_minimum,lights_left,lights_right,lights_brake,lights_reverse,lights_warning,ignition,emergency,auto_ignition,auto_brake,auto_direction,auto_clutch,priority,lifetime

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlcCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.clutch is None:
        self.clutch = 0.
      if self.brake is None:
        self.brake = 0.
      if self.steering_wheel is None:
        self.steering_wheel = 0.
      if self.rpm is None:
        self.rpm = 0.
      if self.lights_high is None:
        self.lights_high = 0
      if self.lights_medium is None:
        self.lights_medium = 0
      if self.lights_minimum is None:
        self.lights_minimum = 0
      if self.lights_left is None:
        self.lights_left = 0
      if self.lights_right is None:
        self.lights_right = 0
      if self.lights_brake is None:
        self.lights_brake = 0
      if self.lights_reverse is None:
        self.lights_reverse = 0
      if self.lights_warning is None:
        self.lights_warning = 0
      if self.ignition is None:
        self.ignition = 0
      if self.emergency is None:
        self.emergency = 0
      if self.auto_ignition is None:
        self.auto_ignition = 0
      if self.auto_brake is None:
        self.auto_brake = 0
      if self.auto_direction is None:
        self.auto_direction = 0
      if self.auto_clutch is None:
        self.auto_clutch = 0
      if self.priority is None:
        self.priority = 0.
      if self.lifetime is None:
        self.lifetime = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.clutch = 0.
      self.brake = 0.
      self.steering_wheel = 0.
      self.rpm = 0.
      self.lights_high = 0
      self.lights_medium = 0
      self.lights_minimum = 0
      self.lights_left = 0
      self.lights_right = 0
      self.lights_brake = 0
      self.lights_reverse = 0
      self.lights_warning = 0
      self.ignition = 0
      self.emergency = 0
      self.auto_ignition = 0
      self.auto_brake = 0
      self.auto_direction = 0
      self.auto_clutch = 0
      self.priority = 0.
      self.lifetime = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4d14I2d().pack(_x.clutch, _x.brake, _x.steering_wheel, _x.rpm, _x.lights_high, _x.lights_medium, _x.lights_minimum, _x.lights_left, _x.lights_right, _x.lights_brake, _x.lights_reverse, _x.lights_warning, _x.ignition, _x.emergency, _x.auto_ignition, _x.auto_brake, _x.auto_direction, _x.auto_clutch, _x.priority, _x.lifetime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.clutch, _x.brake, _x.steering_wheel, _x.rpm, _x.lights_high, _x.lights_medium, _x.lights_minimum, _x.lights_left, _x.lights_right, _x.lights_brake, _x.lights_reverse, _x.lights_warning, _x.ignition, _x.emergency, _x.auto_ignition, _x.auto_brake, _x.auto_direction, _x.auto_clutch, _x.priority, _x.lifetime,) = _get_struct_4d14I2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_4d14I2d().pack(_x.clutch, _x.brake, _x.steering_wheel, _x.rpm, _x.lights_high, _x.lights_medium, _x.lights_minimum, _x.lights_left, _x.lights_right, _x.lights_brake, _x.lights_reverse, _x.lights_warning, _x.ignition, _x.emergency, _x.auto_ignition, _x.auto_brake, _x.auto_direction, _x.auto_clutch, _x.priority, _x.lifetime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 104
      (_x.clutch, _x.brake, _x.steering_wheel, _x.rpm, _x.lights_high, _x.lights_medium, _x.lights_minimum, _x.lights_left, _x.lights_right, _x.lights_brake, _x.lights_reverse, _x.lights_warning, _x.ignition, _x.emergency, _x.auto_ignition, _x.auto_brake, _x.auto_direction, _x.auto_clutch, _x.priority, _x.lifetime,) = _get_struct_4d14I2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d14I2d = None
def _get_struct_4d14I2d():
    global _struct_4d14I2d
    if _struct_4d14I2d is None:
        _struct_4d14I2d = struct.Struct("<4d14I2d")
    return _struct_4d14I2d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
